MVCApp/Models/DogViewModel.cs
namespace MVCApp.Models
{
    public class DogViewModel
    {
        public string? Name { get; set; }
        public int Age { get; set; }
        public string? Breed { get; set; }
    }
}

MVCApp/Models/ErrorViewModel.cs
namespace MVCApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCApp/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApp.Models;

namespace MVCApp.Controllers
{
    public class HelloWorldController : Controller
    {
        //persist a single dogs list; doesnt need an instance of the controller
        private static List<DogViewModel> dogs = new List<DogViewModel>();
        public IActionResult Index()
        {
            return View(dogs);
        }

        public IActionResult Create()
        {
            DogViewModel dogViewModel = new DogViewModel();
            return View(dogViewModel); //data binding - Controller > View
        }

        public IActionResult CreateDog(DogViewModel newDog)
        {
            dogs.Add(newDog);
            return RedirectToAction(nameof(Index));
        }


    }
}

MVCApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCApp.Models;
using System.Diagnostics;

namespace MVCApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        //CTOR
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCApp/Views/HelloWorld/Create.cshtml
@model DogViewModel
@{
    ViewData["Title"] = "Create Page";
}

<h1>Create</h1>
<hr />
<div class="row">
    <div class="col-6">

        <div class="card">
            <div class="card-header">
                <h5>Create a new dog</h5>
            </div>
            <div class="card-body">
                <form asp-controller="HelloWorld" asp-action="CreateDog" method="post">
                    <div class="mb-3">
                        <label class="form-label">Dog Name</label>
                        <input asp-for="Name" type="text" class="form-control" />
                    </div>
                    <div class="mb-3">

                        <label class="form-label">Dog Age</label>
                        <input asp-for="Age" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">

                        <label class="form-label">Dog Breed</label>
                        <input asp-for="Breed" type="text" class="form-control" />
                    </div>
                    <div class="mb-3">

                        <button class="btn btn-primary" type="submit">
                            Create Dog
                        </button>
                    </div>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>

MVCApp/Views/HelloWorld/Index.cshtml
@model List<MVCApp.Models.DogViewModel>
@{
    ViewData["Title"] = "Dog List Page";
}

<ul>
    @foreach(var dog in Model)
    {
        <li>@dog.Name (@dog.Age)</li>
        <li>@dog.Breed</li>
    }
</ul>

MVCApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Dog Factory</h1>
    <p>A brief refresher on ASP.NET MVC application design</p>
</div>

MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dog App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Index">Dog List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>